config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    resources :tasks
  end

    resources :profiles, only: [:new, :create, :show, :edit, :update]

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'     => 'users#new'

  root to: 'home_page#home'



  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  msg = ' name must be in range between 3 and 20 characters'
  belongs_to :user
  validates :user, presence: true
  validates :title, :description, presence: true
  validates :title, length: { in: 3..20,
                              message: msg }
  validates :description, length: {
    maximum: 200,
    too_long: '%{count} characters is the maximum allowed!'
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
require 'securerandom'

  after_create :build_profile

  has_secure_password
  has_many :tasks, dependent: :destroy
  has_one :profile, dependent: :destroy

  validates :username, :email, :password,
            :password_confirmation, presence: true
  validates :email, :username, uniqueness: true
  validates :password, confirmation: true

  validates :username, length: { minimum: 3 }

  def self.from_omniauth(auth)
      if self.where(email: auth.info.email).exists?
        return_user =self.where(email: auth.info.email).first
      else
        return_user = self.create do |user|
          user.username = auth.info.name
          user.password = user.password_confirmation = SecureRandom.base64(15)
          user.email = auth.info.email
        end
      end
    return_user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/concerns/user_login.rb
# frozen_string_literal: true

module UserLogin
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/controllers/home_page_controller.rb
# frozen_string_literal: true

class HomePageController < ApplicationController
  def home
    @tasks = Task.all
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  before_action :get_profile, only: %i[edit update show]

  def edit; end

  def update
    if @profile.update(profile_params)
      flash[:notice] = 'Profile successfull updated!'
      redirect_to profile_path(current_user)
    else
      flash.now[:alert] = @profile.errors.full_messages
      render 'edit'
    end
  end

  def show; end

  private

  def profile_params
    params.require(:profile).permit(:name, :second_name, :sex,
                                    :birthday, :about, :country)
  end

  def get_profile
    @profile = current_user.profile
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include UserLogin

  def create
    user = User.find_by(email: params.dig(:session, :email))
    if user&.authenticate(params.dig(:session, :password))
      session[:user_id] = user.id
      flash[:notice] = 'Successful log in!'
      redirect_to user_path(user), notice: 'Successful log in!'
    else
      flash[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'See you soon!'
    redirect_to root_url
  end

  def googleAuth
    user = User.from_omniauth(request.env["omniauth.auth"])

    log_in(user)
    puts user.errors.full_messages
    redirect_to root_path
  end

end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :find_task, only: %i[show update edit destroy]
  before_action :check_user?, only: %i[update destroy]

  def index
    @tasks = current_user.tasks.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      flash[:notice] = 'Task successfull add'
      redirect_to user_tasks_path
    else
      flash.now[:alert] = @task.errors.full_messages
      render 'new'
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = 'Task successfull edit'
      redirect_to root_url
    else
      flash.now[:alert] = 'Oops, something going wrong'
      render 'edit'
    end
  end

  def edit; end

  def destroy
    @task.destroy
    flash[:notice] = 'Task successfull deleted'
    redirect_to root_url
  end

  private

  def check_user?
    unless @task.user != current_user
      flash[:alert] = 'You dont have permission to do this!!'
      redirect_to root_url
    end
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :complated)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include UserLogin
  before_action :find_user, only: %i[show destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      flash[:notice] = 'Your account successful created!'
      flash[:notice] = 'Please, fill in your profile'
      redirect_to edit_profile_path(@user)
    else
      flash.now[:alert] = @user.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @user.destroy
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info'
    when 'success' then 'alert alert-success'
    when 'error' then 'alert alert-danger'
    when 'alert' then 'alert alert-warning'
    end
  end
end

app/helpers/home_page_helper.rb
# frozen_string_literal: true

module HomePageHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/home_page/home.html.erb
    <%if @tasks.empty?%>
    <span class="text-warning">There`s no tasks yet...</span>
  <%else%>
    <% @tasks.each do |task| %>
    <table class="table table-bordered table-dark">
      <tr>
        <td><%=link_to task.user.username, user_path(task.user.id)%></td>
        <td align = "right">Created: <%=task.created_at.strftime("%Y-%m-%d, %H:%m")%></td>
        <td><%=link_to "Edit", edit_user_task_path(task.user, task.id)%></td>
        <td><%=link_to "Delete", user_task_path(task.user, task.id), method: :delete, data: {confirm: "Are you sure?"}%></td>
      </tr>
      <tr>
          <table class="table table-bordered table-dark">
              <thead>
                <th>Task</th>
                <th>Details</th>
                <th>Complated</th>
              </thead>
            <tbody>
              <tr>
                <td><%=task.title%></td>
                <td><%=task.description%></td>
                <td><%=task.complated%></td>
              </tr>
            </tbody>
          </table>
          <%if !(task.created_at == task.updated_at) %>
            <i style="font-size:0.75em;">Last updated: <%=task.updated_at.strftime("%Y-%m-%d, %H:%m")%></i>
          <%end%>
      </tr>
    </table>
    <hr style="border: none; border-bottom: 1px solid grey;">
    <%end%>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo list</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand"><%=link_to "Home", root_url%></a>
          </div>

          <%if current_user%>
            <a class="navbar-brand"><%=link_to "Profile", profile_path(current_user.profile) if current_user.profile %></a>
            <a class="navbar-brand"><%=link_to "My tasks", user_tasks_path(current_user)%></a>
            <a class="navbar-brand"><%=link_to "Add new task", new_user_task_path(current_user), method: :get%></a>
            <a class="navbar-brand"><%=link_to "Log out", logout_path, method: :delete%></a>
            <p class="navbar-text">Signed in as: <%=current_user.username%></p>

          <%else%>
            <p class="navbar-text"><%=link_to "Sign Up", signup_path %></p>
            <p class="navbar-text"><%=link_to "Sign In", login_path %></p>
          <%end%>
        </div>
      </nav>


      <div class="jumbotron">
        <h1 align='center'>ToDo list by Zol</h1>
      </div>
      <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
                <%= value %>
          </div>
    <% end %>
    <%= yield %>
    <footer>
      <p align = 'center'>Created by     <%= link_to "Zol", "https://github.com/miwail/ror/" %></p>
    </footer>
    </div>
  </body>
</html>

app/views/profiles/edit.html.erb
<table class="table table-bordered table-dark ">
  <tr>
    <td>
      <%=form_for(@profile, url: profile_path(current_user.profile)) do |f|%>
        <p><%=f.label :name %></p>
        <p><%=f.text_field :name%></p>
        <p><%=f.label :second_name%></p>
        <p><%=f.text_field :second_name%></p>
        <p><%=f.label :sex%></p>
        <p><%=f.text_field :sex%></p>
        <p><%=f.label :country%></p>
        <p><%=f.text_field :country%></p>
        <p><%=f.label :birthday%></p>
        <p><%=f.date_select :birthday%></p>
        <p><%=f.label :about %></p>
        <p><%=f.text_field :about %></p>

        <p><%=f.submit "Update profile", :class => 'btn btn-light'%></p>
      <%end%>
    </td>
  </tr>
</table>

app/views/profiles/show.html.erb
<table class="table table-bordered table-dark" style="width:70%;" align="center">
  <tr>
    <th>Name</th>
    <td><%=@profile.name %></td>
  </tr>
  <tr>
    <th>Second name</th>
    <td><%=@profile.second_name %></td>
  </tr>
  <tr>
    <th>Sex</th>
    <td><%=@profile.sex %></td>
  </tr>
  <tr>
    <th>Birthday</th>
    <td><%=@profile.birthday %></td>
  </tr>
  <tr>
    <th>Country</th>
    <td><%=@profile.country %></td>
  </tr>
  <tr>
    <th>About</th>
    <td><%=@profile.about %></td>
  </tr>

</table>
<div style='text-align: center;'>
  <span>
    <%=link_to 'edit', edit_profile_path(current_user.profile),
                      :class => 'btn btn-dark' %>
  </span>
</div>

app/views/tasks/edit.html.erb
<table class="table table-bordered table-dark">
  <tr>
    <td>
      <%=form_for(@task, url: user_task_path) do |f| %>
        <p><%= f.label :title %></p>
        <p><%= f.text_field :title %></p>
        <p><%= f.label :description %></p>
        <p><%= f.text_field :description %></p>
        <p><%= f.label :Complated? %></p>
        <p><%= f.radio_button:complated, "Complated?", :checked => false%></p>
        <hr>
        <p align="center"><%= f.submit "Update task", :class => 'btn btn-light' %></p>
      <%end%>
    </td>
  </tr>
</table>

app/views/tasks/index.html.erb
<%if @tasks.empty?%>
  <span class="text-warning">There`s no tasks yet...</span>
<%else%>
  <% @tasks.each do |task| %>
  <table class="table table-bordered table-dark">
    <tr>
      <td><%=link_to task.user.username, user_path(task.user.id)%></td>
      <td align = "right">Created: <%=task.created_at.strftime("%Y-%m-%d, %H:%m")%></td>
      <td><%=link_to "Edit", edit_user_task_path(task.user, task.id)%></td>
      <td><%=link_to "Delete", user_task_path(task.user, task.id), method: :delete, data: {confirm: "Are you sure?"}%></td>
    </tr>
    <tr>
        <table class="table table-bordered table-dark">
            <thead>
              <th>Task</th>
              <th>Details</th>
              <th>Complated</th>
            </thead>
          <tbody>
            <tr>
              <td><%=task.title%></td>
              <td><%=task.description%></td>
              <td><%=task.complated%></td>
            </tr>
          </tbody>
        </table>
        <%if !(task.created_at == task.updated_at) %>
          <i style="font-size:0.75em;">Last updated: <%=task.updated_at.strftime("%Y-%m-%d, %H:%m")%></i>
        <%end%>
    </tr>
  </table>
  <hr style="border: none; border-bottom: 1px solid grey;">
  <%end%>
<%end%>

app/views/tasks/new.html.erb
<table class="table table-bordered table-dark">
  <tr>
    <td>
      <%=form_for(@task, url: user_tasks_path) do |f|%>
        <p><%=f.label :title%></p>
        <p><%=f.text_field :title%></p>
        <p><%=f.label :description%></p>
        <p><%=f.text_field :description%></p>
        <hr>
        <p align="center"><%=f.submit "Add task", :class => "btn btn-light"%></p>

      <%end%>
    </td>
  </tr>
</table>

app/views/tasks/show.html.erb
<table>
  <th>ID</th>
  <th>Name</th>
  <th>Description</th>
  <th>Start at</th>
  <th>End at</th>
  <th></th>
  <th></th>
  <th></th>

  <% for @task do |t|%>
    <tr>
      <td><%=link_to t.id,task_path(t.id)%></td>
      <td><%=link_to t.name,task_path(t.id)%></td>
      <td><%=t.description%></td>
      <td><%=t.start_time%></td>
      <td><%=t.end_time%></td>
      <%if t.user %>
        <td><%=t.user.username %></td>
      <%else%>
        <td>Nil</td>
      <%end%>
      <td><%= link_to "Edit", edit_task_path(t)%></td>
      <td><%= link_to "Delete", task_path(t), :method => :delete, data: {confirm:"Are you sure?"} %></td>
    </tr>
  <%end%>
</table>

app/views/users/index.html.erb
<%if @users.empty?%>
  <span class="text-warning">There`s no users yet...</span>
<%else%>
  <table class="table table-bordered table-dark">
    <thead>
      <th>Username</th>
      <th>Email</th>
      <th>Created at</th>
    </thead>
    <tbody>
      <%@users.each do |t|%>
        <tr>
          <td><strong><%=t.username%></strong></td>
          <td><%=t.email%></td>
          <td><%=t.created_at%></td>
        </tr>
      <%end%>
    </tbody>
<%end%>

app/views/users/new.html.erb
  <h1>Create new account</h1>
  <%= form_for @user do |f| %>

        <p><%= f.label :username %></p>
        <p><%= f.text_field :username %></p>
        <p><%= f.label :email %></p>
        <p><%= f.email_field :email%></p>
        <p><%= f.label :password %></p>
        <p><%= f.password_field :password %></p>
        <p><%= f.label :password_confirmation %></p>
        <p><%= f.password_field :password_confirmation %></p>
        <p><strong><%= f.submit "Sign up", class: :"btn btn-dark" %></strong></p>

        <p><strong><%= link_to 'Or, Sign in with google', '/auth/google_oauth2'%></strong></p>
    <%end%>

app/views/users/show.html.erb
<table class="table table-bordered table-dark">
    <thead>
      <th>Username</th>
      <th>Email</th>
      <th>Created at</th>
    </thead>
    <tbody>
        <tr>
          <td><%=@user.username%></td>
          <td><%=@user.email%></td>
          <td><%=@user.created_at%></td>
        </tr>
    </tbody>
</table>